
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: special-winter-shoe-repo
spec:
  interval: 1m0s
  url: https://github.com/waciumawanjohi/special-winter-shoe
  ref:
    branch: main
